### ISSUE TITLE
payment_type in productTransaction model

### ISSUE THREAD

**Issue by jboyd79** [virajkothari7/OnlineRetailPOS#5]
Hello again Viraj,

While I understand the payment_type field in the transaction model,
I do not understand payment_type in the productTransaction model.

Can you explain?

Best Regards,
John.

**Comment by virajkothari7** [comment]
I guess technically you don't need it, I just put it for chart/visualization so I don't have to do join, some calculation. I mean if you want your db to be optimized you can remove it, but do make sure that you update the methods in view wherever payment type from productTransaction is used.

**Comment by jboyd79** [comment]
Thanks for the info Viraj.
Much appreciated.

Regards,
John.
